version: '3.8'
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db-12:/var/lib/postgresql/data
  web:
    image: web
    links:
      - api
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  api:
    image: api
    links:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    
volumes:
  db-12:
    driver: local